/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#121317",
        "secondary-container": "#444749",
        "surface": "#121317",
        "outline": "#9a8f7e",
        "on-secondary": "#2e3132",
        "tertiary": "#b0c6ff",
        "on-secondary-fixed": "#191c1e",
        "inverse-primary": "#795900",
        "tertiary-fixed": "#d9e2ff",
        "on-tertiary": "#112e64",
        "background": "#121317",
        "on-secondary-fixed-variant": "#444749",
        "on-primary-container": "#4f3900",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-surface": "#e3e2e7",
        "primary": "#ebc165",
        "surface-container-highest": "#343439",
        "primary-container": "#c9a24a",
        "on-tertiary-fixed": "#001945",
        "on-primary": "#3f2e00",
        "surface-tint": "#ebc165",
        "on-primary-fixed-variant": "#5b4300",
        "tertiary-container": "#8ea6e4",
        "primary-fixed-dim": "#ebc165",
        "surface-container-lowest": "#0d0e12",
        "secondary-fixed-dim": "#c5c6c8",
        "on-surface-variant": "#d1c5b2",
        "on-background": "#e3e2e7",
        "outline-variant": "#4e4637",
        "surface-container-low": "#1a1b20",
        "secondary-fixed": "#e1e2e4",
        "on-primary-fixed": "#261a00",
        "inverse-surface": "#e3e2e7",
        "surface-container-high": "#292a2e",
        "inverse-on-surface": "#2f3035",
        "error": "#ffb4ab",
        "primary-fixed": "#ffdf9e",
        "on-tertiary-fixed-variant": "#2c457c",
        "error-container": "#93000a",
        "surface-bright": "#38393d",
        "on-tertiary-container": "#203a71",
        "surface-container": "#1e1f24",
        "secondary": "#c5c6c8",
        "tertiary-fixed-dim": "#b0c6ff",
        "surface-variant": "#343439",
        "on-secondary-container": "#b4b5b7",
        "canvas": "#050505",
        "surface-1": "#0B0B0D",
        "surface-2": "#121317",
        "surface-3": "#1A1C21",
        "elevated": "#202329",
        "soft-divider": "#242830",
        "strong-divider": "#353B45",
        "wood-dark": "#2D1B15",
        "wood-light": "#3E2723",
        "metal": "#C8CDD3"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"Courier New"', 'Courier', 'monospace'],
      },
    },
  },
  plugins: [],
}
